# Generated by Django 4.0.2 on 2024-06-28 18:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_describtion_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/broken-1.png', upload_to=products.models.product_image_file_path),
        ),
    ]
